plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
	maven {
		name = "Fabric"
		url = "https://maven.fabricmc.net/"
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
	maven {
		name = "CurseMaven"
		url = "https://www.cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/releases"
	}
}

loom {
	splitEnvironmentSourceSets()

	mixin {
		useLegacyMixinAp = true
		defaultRefmapName = "historystages.refmap.json"
	}

	mods {
		"historystages" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	//JADE
	modImplementation "maven.modrinth:jade:15.10.5+fabric"
	//JEI
	modImplementation "maven.modrinth:jei:19.27.0.340"
	//EMI
	modCompileOnly "dev.emi:emi-fabric:1.1.24+1.21.1:api"
	//FTBQuest
	modCompileOnly "curse.maven:ftb-library-fabric-438495:7746958"
	modCompileOnly "curse.maven:ftb-teams-fabric-438497:7878280"
	modCompileOnly "curse.maven:ftb-quests-fabric-438496:7878288"
	//Lootr
	modImplementation "curse.maven:lootr-fabric-615106:8041235"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.name}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
